add ribbon bar implementation for extenstion
MoebiusSolutions/extension-scaffold pull request #12
Opened 2023-09-19 14:12 UTC by nickanna42

This PR makes some small, non-breaking requests to the ribbon panel implementation of ES. Specifically, it allows for the host application to provide React components to the client extensions via an attribute on the ES object that is passed to the extensions.

2023-09-19 17:11 UTC, itechify commented
Is this PR updating an example extension to show how this can currently be done? Just wanted to confirm that is the case since I don't see any changes to es-runtime / es-home.

2023-09-25 16:29 UTC, nickanna42 commented
> Is this PR updating an example extension to show how this can currently be done? Just wanted to confirm that is the case since I don't see any changes to es-runtime / es-home.

This is all the code that is needed. The frontend framework implements the spec defined in the api beforing passing the extension-scaffold object to the activate function and places the host elements on the page according to the static application resources for the app.

I have updated it to allow for the implementation to optionally add react components onto the extension-scaffold object for the convience of the extensions that implement the `activate` spec to have access to consistently themed components provided by the frontend framework.

2023-09-25 18:04 UTC, moesol requested changes

2023-09-25 18:04 UTC, moesol commented on es-runtime/src/es-api.ts
> -        [key: string]: HTMLElement
We have users of ES that use Angular or other non-React frameworks.

We do not want to be tied to React in the API. We do want to allow React components to use the API and to be ribbon items, etc. We have examples of that use case.

2023-09-26 14:11 UTC, moesol requested changes

2023-09-26 14:11 UTC, moesol commented on es-runtime/package.json
> +    "react": "^17.0.2",
We do not want to add react as a dependency.

Nothing in es-runtime requires it.
If extensions want to use React, they can import it.

2023-09-29 14:18 UTC, nickanna42 commented
I was able to overload the typing in applications/extensions in lieu of this PR.

2023-09-29 14:18 UTC, closed without merging